env: dev
disabled: false
expiration: 300
metadata:
  platform: "node-alpine"
  editor:
    hide: false
    srcDir: ""
  proxy:
    ports:
    - port: 3000
      hide: false
      tabs:
      - name: "Example"
        path: "/"
      - name: "Example 2"
        path: "/index.html"
  env:
    vars:
    - name: var1
      defaultValue: "val"