env: dev
disabled: false
runtime:
  platform: "node-alpine"
  command: "npm install && npm start"
  port: 3000
  env:
    var1: "value1"
metadata:
  env:
    vars:
    - name: var1
      defaultValue: "val"
  editorTab:
    hide: false
    srcDir: ""
  appTabs:
  - port: 3000
    hide: false
    name: "Example"
    path: "/"
  - port: 3000
    hide: false
    name: "Example 2"
    path: "/index.html"
